#!/usr/bin/env sh

limelight -m config width                   3
limelight -m config radius                  12
limelight -m config placement               interior
limelight -m config active_color            0xFF0B9BE3 #0xCC999900 #0xCC606060
limelight -m config normal_color            0xFF202020
limelight -m config insert_feedback_color   0x00000000

echo "limelight configuration loaded.."


#example

#limelight -m config width 3
#limelight -m config radius 10
#limelight -m config placement exterior
#limelight -m config active_color 0xFF40FF00
#limelight -m config normal_color 0x00FFFFFF