#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --loßad-sa"

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
#yabai -m space 1 --label one
#yabai -m space 2 --label two
#yabai -m space 3 --label three
#yabai -m space 4 --label four
#yabai -m space 5 --label five
#yabai -m space 6 --label six
#yabai -m space 9 --label nine

# float system preferences. Most of these just diable Yabai form resizig them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Music$" sticky=on manage=off
yabai -m rule --add app="^HP Prime$" sticky=on manage=off
yabai -m rule --add app="^Messages$" sticky=on manage=off
yabai -m rule --add app="^Logitech G HUB$" sticky=on manage=off
yabai -m rule --add app="^Calendar$" sticky=on manage=off
yabai -m rule --add app="^Zoom$" sticky=on manage=off
yabai -m rule --add app="^Mail$" sticky=on manage=off
yabai -m rule --add app="^WhatsApp$" sticky=on manage=off
yabai -m rule --add app="^Messenger$" sticky=on manage=off
yabai -m rule --add app="^Python$" sticky=on manage=off
yabai -m rule --add app="^FaceTime$" sticky=on manage=off
yabai -m rule --add app="^AnyDesk$" sticky=on manage=off
yabai -m rule --add app="^Keychain Access$" sticky=on manage=off
yabai -m rule --add app="^FaceTime$" sticky=on manage=off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on #float
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.97

# these are for the less secure version, to adjust border go to limelightrc instead
yabai -m config window_border                off
#yabai -m config width 3
#yabai -m config radius 12
#yabai -m config active_color                0xCC606060
#yabai -m config normal_color                0xFF202020
#yabai -m config insert_feedback_color       0x00000000
yabai -m config window_border_width          5
yabai -m config border_placement             interior
yabai -m config active_window_border_color   0xFF0B9BE3 #0xCC606060 #0xFF202020
yabai -m config normal_window_border_color   0xFF202020 #0x00FFFFFF
yabai -m config insert_feedback_color        0x00000000 #0xFFD75F5F

# some other settings
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp #bsp #float
# yabai -m space --padding abs:20:20:20:20
# yabai -m space --gap abs:20
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

# Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
limelight &>/dev/null &

echo "yabai configuration loaded.."

# end